# -*- coding: utf-8 -*-
"""Klasifikasi Buah Apel dan Jeruk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C9jeeBsiEra-saNjSfKnncSGHgx-AnGs
"""

from google.colab import files
uploaded = files.upload()

import zipfile

with zipfile.ZipFile('Dataset.zip', 'r') as zip_ref:
    zip_ref.extractall()

import os

print(os.listdir("Dataset"))

import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential

IMG_SIZE = (100,100)
BATCH_SIZE = 32

train_ds = tf.keras.utils.image_dataset_from_directory(
    "Dataset",
    validation_split=0.2,
    subset="training",
    seed=123,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

val_ds = tf.keras.utils.image_dataset_from_directory(
    "Dataset",
    validation_split=0.2,
    subset="validation",
    seed=123,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

model = Sequential([
    layers.Rescaling(1./255),

    layers.Conv2D(16,3,activation='relu'),
    layers.MaxPooling2D(),

    layers.Conv2D(32,3,activation='relu'),
    layers.MaxPooling2D(),

    layers.Conv2D(64,3,activation='relu'),
    layers.MaxPooling2D(),

    layers.Flatten(),

    layers.Dense(128,activation='relu'),

    layers.Dense(2,activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=10
)

model.save("fruit_model.h5")
print("Model berhasil disimpan")

print("Akurasi Training Terakhir :", history.history['accuracy'][-1])
print("Akurasi Validasi Terakhir :", history.history['val_accuracy'][-1])

import matplotlib.pyplot as plt

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])

plt.title('Akurasi Model')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Training', 'Validation'])

plt.show()

from google.colab import files

uploaded = files.upload()

from tensorflow.keras.preprocessing import image
import matplotlib.pyplot as plt

img = image.load_img("apel.jpg")

plt.imshow(img)
plt.axis("off")
plt.show()

import tensorflow as tf
import numpy as np
from tensorflow.keras.preprocessing import image
import matplotlib.pyplot as plt

# Load model
model = tf.keras.models.load_model("fruit_model.h5")

# Load gambar
img_path = "apel.jpg"

img = image.load_img(img_path, target_size=(100,100))
img_array = image.img_to_array(img)

# Normalisasi
img_array = img_array / 255.0

# Tambah dimensi batch
img_array = np.expand_dims(img_array, axis=0)

# Prediksi
prediction = model.predict(img_array)

# Nama kelas
class_names = ["Apel", "Jeruk"]

predicted_class = class_names[np.argmax(prediction)]
confidence = np.max(prediction) * 100

# Tampilkan gambar
plt.imshow(img)
plt.axis("off")
plt.title(f"Prediksi: {predicted_class}")
plt.show()

print(f"Hasil Prediksi : {predicted_class}")
print(f"Tingkat Keyakinan : {confidence:.2f}%")
print("Probabilitas :", prediction)

print(train_ds.class_names)

from google.colab import files

uploaded = files.upload()

from tensorflow.keras.preprocessing import image
import matplotlib.pyplot as plt

img = image.load_img("apel.jpg")

plt.imshow(img)
plt.axis("off")
plt.show()

import tensorflow as tf
import numpy as np
from tensorflow.keras.preprocessing import image
import matplotlib.pyplot as plt

# Load model
model = tf.keras.models.load_model("fruit_model.h5")

# Load gambar
img_path = "apel.jpg"

img = image.load_img(img_path, target_size=(100,100))
img_array = image.img_to_array(img)

# Normalisasi
img_array = img_array / 255.0

# Tambah dimensi batch
img_array = np.expand_dims(img_array, axis=0)

# Prediksi
prediction = model.predict(img_array)

# Nama kelas
class_names = ["Apel", "Jeruk"]

predicted_class = class_names[np.argmax(prediction)]
confidence = np.max(prediction) * 100

# Tampilkan gambar
plt.imshow(img)
plt.axis("off")
plt.title(f"Prediksi: {predicted_class}")
plt.show()

print(f"Hasil Prediksi : {predicted_class}")
print(f"Tingkat Keyakinan : {confidence:.2f}%")
print("Probabilitas :", prediction)